Repository edgecomllc/eupf, pull requests merged in 2023-07, with the labels that each got.

#327 refactor: avoid pointer arithmetic with `void*`
  cmd/ebpf/xdp/n3n6_entrypoint.c
  cmd/ebpf/xdp/utils/gtp_utils.h
  cmd/ebpf/xdp/utils/packet_context.h
  cmd/ebpf/xdp/utils/parsers.h
Labels: good first issue

#346 fix: NodeId can be an ip address
  cmd/config/config.go
Labels: bug

#347 fix: Search for Transport Level Marking values in child IEs. Add Pytest session creation and deletion cycle, with heartbeat response.
  .github/workflows/test.yml
  .gitignore
  cmd/core/display_utils.go
  cmd/core/get_transport_level_marking_test.go
  cmd/core/pfcp_connection.go
  cmd/core/pfcp_handlers.go
  cmd/core/pfcp_session_handlers.go
  pytest/test_session.py
  scripts/scapy/SessionEstablishmentRequest.py
  scripts/scapy/SessionModificationRequest.py
Labels: bug, N4, ebpf

#357 fix: Session deletion code typo. Ipv4->Ipv6
  cmd/core/pfcp_connection.go
Labels: bug

#379 fix: Recovery timestamp was not sending UPF starting time, and node association entity seen time in hearbeats.
  cmd/core/node_association.go
  cmd/core/pfcp_connection.go
  cmd/core/pfcp_handlers.go
  cmd/core/pfcp_hearbeat.go
Labels: bug, pfcp, N4

#380 feat: Add new metric `upf_pfcp_current_sessions`
  cmd/core/metrics.go
  cmd/core/pfcp_connection.go
  cmd/main.go
  docs/metrics.md
Labels: help wanted, monitoring
